### ISSUE TITLE
Setting secure cookie on plain HTTP is not allowed

### ISSUE THREAD

**Issue by pa-purpura** [mschwager/docker-simplesamlphp#3]
Hi @mschwager,

first of all thank you for your work, it was very useful to me. 

Then, i installed simplesamlphp-v.2.0.6 and your docker, locally (I changed the version in the bootstrap.sh file), I followed every step and when I click on http://localhost/simplesaml/index.php. everything works fine.

I changed the settings in config.php to enable the admin, but when i click on http://localhost/simplesaml/module.php/admin/.
I have an error:

"SimpleSAML\Error\CriticalConfigurationError: The configuration is invalid: Setting secure cookie on plain HTTP is not allowed."

I tried to change 'baseurlpath' and application array ('baseURL') and 'session.cookie.secure' to false, but still not working.

do you have any tips?

**Comment by mschwager** [comment]
Hi there! I believe I ran into a similar issue when running over HTTP.

You're on the right track, here's the full list of settings I ended up changing:

- `session.cookie.secure` -> `false`
- `session.cookie.samesite` -> `null`
- `language.cookie.secure` -> `false`
- `language.cookie.samesite` -> `null`

Let me know if this fixes it and I can document these  settings in the README :+1:

**Comment by pa-purpura** [comment]
Hi! thanks for your help.

Ok it seems it works but i'm not sure at the moment cause i get another issue: "SimpleSAML\Error\ConfigurationError: The configuration (config/authsources.php) is invalid: Missing configuration file". I'm going to solve that and then I will tell you, if u can put these fixes in the README.

**Comment by mschwager** [comment]
That likely means you need to copy `.storage/config/authsources.php.dist` -> `.storage/config/authsources.php`.

It sounds like you have SSP working with Docker Compose, so from here you'll need to run through the installation and configuration process according to your needs (SP or IdP or both). I would start with these docs:

- https://simplesamlphp.org/docs/stable/simplesamlphp-install.html#upgrading-configuration-files
- https://simplesamlphp.org/docs/stable/simplesamlphp-sp.html
- https://simplesamlphp.org/docs/stable/simplesamlphp-idp.html

Configuration for SSP is very well documented on their site, and largely outside the scope of this project (it exists mostly to show a very basic Dockerized workflow). Good luck with your SAML implementation!

**Comment by pa-purpura** [comment]
Ok thanks a lot, it works! you can put the settings above, inside the README to fix this kind of issue.

**Comment by pa-purpura** [comment]
Ok thanks a lot, it works! you can put the settings above, inside the README to fix this kind of issue.

**Comment by mschwager** [comment]
Done! https://github.com/mschwager/docker-simplesamlphp/commit/76bc106976f643eb90020e6df0f136e14e13c3f3

**Comment by hwood-vivup** [comment]
I did guess this is what I needed to do, but this could be in the README too no?:

copy the config files:
`.storage/config/config.php.dist` -> `storage/config/config.php`
`.storage/config/authsources.php.dist` -> .`storage/config/authsources.php`
